### ISSUE TITLE
Trusted Committer: synchronize article markdowns from O'Reilly back into github

### ISSUE THREAD

**Issue by Ludmila-N** [InnerSourceCommons/InnerSourceLearningPath#157]
We've been informed that O'Reilly editors have made their changes to the Trusted Committer article, and [we have the results in pdf format](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/58).
We are still [making content changes](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/41) to the article and need to sync the final markdowns from O'Reilly back to this project.

**Comment by rrrutledge** [comment]
Thanks for opening, Ludmila!

**Comment by lenucksi** [comment]
#166 tracks needed format conversion

**Comment by lenucksi** [comment]
Since #195 is merged now all our content is in ASCIIdoc format. 
Also, our repo now is the upstream for O'Reilly too and the Atlas repositories are downstream repos since the successful closing of #108.

Thus we can manually merge the already existing edits in the Atlas ASCIIdoc repositories into our repository and solve that way.
We have edited content for the Trusted Committer Segment and the Introduction segment already.

**Comment by rrrutledge** [comment]
Some edits are merged on, others still pending.

**Comment by rrrutledge** [comment]
https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/262 is the last one.

**Comment by Ludmila-N** [comment]
Closing this issue as all relevant PRs have been merged.

**Comment by rrrutledge** [comment]
Hooray!  Excellent!
