### ISSUE TITLE
Additional Thoughts on the Introductory Article

### ISSUE THREAD

**Issue by guywmartin** [InnerSourceCommons/InnerSourceLearningPath#23]
#22 

Here are some additional thoughts on this first introductory article:

Overall, I think this is a great start - it's thorough and covers the topic in an appropriate level of detail.  

Some potential issues I found were:

- Should this be an article in the 1st person (who is I or we?)

- On Line 214, a statement was made about InnerSource being done during working hours, vs. 'after hours' contributions for Open Source.  That may be the case in some companies, but there are a lot of companies where InnerSource and Open Source contributions happen during working hours.  The vast majority of open source software is built by engineers working on company time to achieve business goals.  I think we should consider removing or rewording that section.

- There are a couple of descriptions of 'Newbies' or 'Newbie tasks', which I think sound a bit demotivating to those who may be 'newbies'.  Let's brainstorm a new name for those community members.

-  There is a lot of focus on TCs being community managers, as well as deep technical experts.  In some communities, you may be able to consider separating the roles so that a dedicated community manager can take on some of those.  This could be especially important if a TC has a deep technical passion, for example, but has a hard time interacting or promoting the project within an internal organization.

**Comment by gruetter** [comment]
/CC @guywmartin , @rrrutledge , @cewilliams , @maxcapraro 

> Should this be an article in the 1st person (who is I or we?)

My gut feeling is to go with _we_ (the InnerSourceCommons Community) instead of _I_. Ok for everybody?  I used _I_ because the article served as the script for the TC video recording.

> [...] InnerSource being done during working hours, vs. 'after hours' contributions for Open Source [...]

You are right, @guywmartin. I propose to remove this. Any objections?

> [...] Newbie tasks [...]

I wasn't aware that _Newbie_ would be demotivating. Some ideas (from a non-native speaker).
Instead of _Newbie_:
- _Beginner_
- _Novice_
- _Newcomer_ (my favorite)

Instead of a _Newbie task_ tag:
- _Good for beginners_
- _First contribution_

Other ideas, everybody?

> There is a lot of focus on TCs being community managers, as well as deep technical experts. In some communities, you may be able to consider separating the roles so that a dedicated community manager can take on some of those. This could be especially important if a TC has a deep technical passion, for example, but has a hard time interacting or promoting the project within an internal organization.

I'm torn on that one, @guywmartin . I see your point and at first glance it would seem unreasonable to deny a deeply technical person who cares about the product built in the community the TC role. In my personal experience, though, in order to be an effective TC, community management skills are essential. In the section _Responsibilities_, four out of five responsibilities are community oriented. I have always had co-TCs in my community which helped share the community leadership workload but I don't think I would have been effective without focusing on both tech stuff and the community. 

What does everybody else think?

**Comment by rrrutledge** [comment]
> My gut feeling is to go with we

I like "we".

> Instead of Newbie

I like "Newcomer" too.

> In my personal experience, though, in order to be an effective TC, community management skills are essential

Yes and the reverse as well - in order to effectively manage a technical community you need the technical skills to back it up.

Also my gut feel is that _many_ (or **most**) inner source projects will be small to the point where they're not funded enough to have enough people to separate out these roles, so TC and community manager will tend to the be same.  I like coupling them.

**Comment by gruetter** [comment]
> Also my gut feel is that many (or most) inner source projects will be small to the point where they're not funded enough to have enough people to separate out these roles, so TC and community manager will tend to the be same.

That's also my experience.

**Comment by gruetter** [comment]
@guywmartin : Before I forget - thanks a lot for your feedback and sorry for not having responded earlier!
