### ISSUE TITLE
Content Outline

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#33]
Per [the schedule](https://docs.google.com/document/d/1QtjQ-qy9bBaPob3V1OldjENTqvj6USIQCjMomKs0XEQ) we'd need an outline for the content of the **Contributor** section of the learning path.

The outline should include a listing of the segments of the learning path as well as the major points of each segment.

Once this outline is finished we can simultaneously start producing both the written and video portions of the segments.

**Comment by rrrutledge** [comment]
Started brainstorming some ideas in [these notes](https://paypalflow.slack.com/archives/CARTU4XV2/p1548443862048400).

**Comment by KathrynKLewis** [comment]
The outline overall looks very good and comprehensive. My only suggestion is to add further detail for clarity to the section: 
- Understand that you have to ‘sell’ your idea - communicate early and often -before- investing a lot of time in coding an idea (fail fast)

What best practices might be shared so that the reader/contributor knows how to "sell" their idea? I imagine there is a framework or protocol to follow so that the contributor is helpful to the owner rather then needy/burdensome.

**Comment by rrrutledge** [comment]
Thank you, @KathrynKLewis

**Comment by guywmartin** [comment]
Thank you @KathrynKLewis - I'll add a quick note that we need to address this in the final video script.
