### ISSUE TITLE
Translate the "Contributor" articles to spanish

### ISSUE THREAD

**Issue by fioddor** [InnerSourceCommons/InnerSourceLearningPath#436]
Create a subdirectory `es` and place translated copies of:

- [x] [Introduction](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc)
- [x] [Becoming an InnerSource Contributor](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/02-becoming-a-contributor-article.asciidoc)
- [x] [Contributor Ethos](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/03-contributor-ethos-article.asciidoc)
- [x] [Mechanics of contributing](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/04-mechanics-of-contributing-article.asciidoc)
- [x] [Benefits of becoming an InnerSource Contributor](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/05-benefits-of-contribution-article.asciidoc)
- [x] [Conclusion](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/06-conclusion-article.asciidoc)

Suggested tip: Let an automatic translator do the heavy lifting and concentrate on correcting and improving from there.
cc: @dicortazar, @JFernando122.

**Comment by fioddor** [comment]
@rrrutledge, @tsadler1988 As _collaborator_ I cannot assign labels or projects.

**Comment by JFernando122** [comment]
Hi, i got a new job so i don't have as much time as i had before. I can do it on saturday-sunday if no one else is doing it already

**Comment by Sergih28** [comment]
Hi! 👋

I'd like to work on this. The suggested tip will help me get it done faster for sure 😃

**Comment by lenucksi** [comment]
> Hi! wave
> 
> I'd like to work on this. The suggested tip will help me get it done faster for sure smiley

Be very welcome to do so! Looking forward to your work.

**Comment by Sergih28** [comment]
I started working on this.

Do you want me to create PRs whenever I finish each file, or wait until I have all of them?

So far I did the _index_ and _introduction_ files.

**Comment by fioddor** [comment]
"Release early, release fast". Small, independent pieces are not only
easier and faster to finish, but also easier and faster to review. :-)

Welcome onboard, BTW!

**Comment by Sergih28** [comment]
Let me know if I'm on the right track before continuing with the rest of translations 👍

**Comment by rrrutledge** [comment]
Welcome onboard!  Glad you're here!  You can also ask questions in the #learning-path channel of the [InnerSource Commons Slack](https://innersourcecommons.org/slackinvite)

**Comment by rrrutledge** [comment]
> Let me know if I'm on the right track before continuing with the rest of translations 👍

@Sergih28 this initial translation works great!  It is out there on [the innersourcecommons.org website](https://innersourcecommons.org/es/learn/learning-path/contributor/01/) with your name on it!  Please do follow the same process on the other articles in this section.  Great stuff!

**Comment by tsadler1988** [comment]
Closing #449 made this close - wonder if we need to change our automation rules as #449 was only for one segment.

**Comment by tsadler1988** [comment]
> Closing #449 made this close - wonder if we need to change our automation rules as #449 was only for one segment.

Looks like this is GitHub behaviour for [linked PRs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) - all we can do is stop linking PRs as far as I can tell.

**Comment by nysenthil** [comment]
Last week I did a machine translation of "Benefits of becoming an InnerSource Contributor" using the IBM Language Translation software. One of my native Spanish Speaking colleagues here in my IBM building volunteered and verified the machine translation text by adding a few corrections of his own. He also suggested that it is better to leave terms such as "upstream" and "bus factor" as it is since there is no adequate Spanish translation available. I'm attaching the verified Spanish translated text here for you to use it.

**Comment by nysenthil** [comment]
Hi Tom and Russ,
Last week I did a machine translation of "Benefits of becoming an InnerSource Contributor" by using our IBM Language Translation software. One of my native Spanish Speaking colleagues here in my IBM building (Ray Valdez) volunteered and verified the machine translated text by adding a few corrections of his own. He also suggested that it is better to leave terms such as "upstream" and "bus factor" as it is since there is no adequate Spanish translation available. I'm attaching the verified Spanish translated text here for you to use it.

**Comment by nysenthil** [comment]
Hi Tom and Russ,
Last week I did a machine translation of "Benefits of becoming an InnerSource Contributor" by using our IBM Language Translation software. One of my native Spanish Speaking colleagues here in my IBM building (Ray Valdez) volunteered and verified the machine translated text by adding a few corrections of his own. He also suggested that it is better to leave terms such as "upstream" and "bus factor" as it is since there is no adequate Spanish translation available. I'm attaching the verified Spanish translated text here for you to use it.
[Benefits-Of-Becoming-An-Inner-Source-Contributor-Spanish-Machine-Translation-Verified.txt](https://github.com/InnerSourceCommons/InnerSourceLearningPath/files/8694139/Benefits-Of-Becoming-An-Inner-Source-Contributor-Spanish-Machine-Translation-Verified.txt)

**Comment by rrrutledge** [comment]
Great, @nysenthil ❗  We can use next week's meeting to go through the process of getting these into a pull request.  Very much looking forward to it ❗

**Comment by tjohnson31415** [comment]
Turns out we had already committed the translation to doc 05 in https://github.com/InnerSourceCommons/InnerSourceLearningPath/pull/471 during one of the working sessions, so I think this issue is complete.
