### ISSUE TITLE
Video Proposal

### ISSUE THREAD

**Issue by rrrutledge** [InnerSourceCommons/InnerSourceLearningPath#49]
Before filming O'Rielly needs us to fill out this [Video Proposal](https://docs.google.com/document/d/1cumudtnptwTomt3cB20QzHDT5mYfhKnT6KMAGN_agxw/edit).  We'll do this by first making a PR to [this markdown version of the document](https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/video-proposal.md).  Once that is approved and merged we can copy the text there into the GDoc that O'Reilly will see.

**Comment by rrrutledge** [comment]
@clobner which of the columns do we need to fill out?  They're not all self-explanatory and some of them appear to be geared toward O'Reilly staff instead of the content author.

**Comment by clobner** [comment]
@rrrutledge You can ignore these fields at the top:


> Editor:
> PA: 
> Instructor:
> Curriculum team member: 
> 
> Shoot Date:

[Here is the proposal for Product Owners](https://docs.google.com/document/d/1aYq4lqYLBymFS_fJhEMWolbAikJCbxpePff_VpBfM-8/edit?usp=sharing) for reference.

**Comment by rrrutledge** [comment]
Thanks, @clobner!  Same question, too, about the [shoot playbook](https://github.com/InnerSourceCommons/InnerSourceLearningPath/issues/47).

**Comment by lenucksi** [comment]
Updated the Google Doc with the recent Video Proposal's draft, since it is merged.
While doing so two things came to mind:
- It would be helpful to have the existing categories for "audience level" such that we can properly select one. Without knowing more "Introductory" or "101" would be something that comes to my mind. @clobner could you provide insight into this one please?
- The author bios can probably only be filled once the content is ready.

**Comment by rrrutledge** [comment]
Great work, Johannes.

**Comment by clobner** [comment]
Proposal and playbook are with the O'Reilly content team for review.

**Comment by clobner** [comment]
This proposal has been approved!

**Comment by rrrutledge** [comment]
Great news!~
